import { Link, useLocation } from "react-router-dom";
import { toPng } from "html-to-image";
import jsPDF from "jspdf";

import {
  ArrowLeft,
  Download,
  Save,
  Maximize2,
  Sparkles,
  Network,
  ShieldCheck,
  Cpu,
  Database,
  Layers3,
  Server,
  FileText,
} from "lucide-react";

import DiagramCanvas from "../components/DiagramCanvas";
import "../styles/dashboard.css";

function CanvasPage() {
  const location = useLocation();

  const savedResult = sessionStorage.getItem("latestArchitectureResult");
  const parsedResult = savedResult ? JSON.parse(savedResult) : null;

  const architectureJson =
    location.state?.architectureJson ||
    parsedResult?.architecture_json ||
    null;

  const scores = parsedResult?.evaluation_scores || {};
  const stack = architectureJson?.technology_stack || {};
  const projectTitle = parsedResult?.project_title || "Architecture Canvas";

  const exportCanvasAsPNG = async () => {
    try {
      const element = document.querySelector(".premium-flow-wrapper");

      if (!element) {
        alert("Canvas not found.");
        return;
      }

      const dataUrl = await toPng(element, {
        cacheBust: true,
        pixelRatio: 2,
        backgroundColor: "#ffffff",
      });

      const link = document.createElement("a");
      link.download = `${projectTitle.replace(/\s+/g, "_")}.png`;
      link.href = dataUrl;
      link.click();
    } catch (error) {
      console.error(error);
      alert("Failed to export canvas.");
    }
  };

  const exportReportAsPDF = () => {
    if (!parsedResult) {
      alert("No architecture report found.");
      return;
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 14;
    let y = 18;

    const addTitle = (text) => {
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text(text, margin, y);
      y += 10;
    };

    const addSection = (title, content) => {
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text(title, margin, y);
      y += 7;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");

      const lines = doc.splitTextToSize(
        String(content || ""),
        pageWidth - margin * 2
      );

      lines.forEach((line) => {
        if (y > 280) {
          doc.addPage();
          y = 18;
        }

        doc.text(line, margin, y);
        y += 5;
      });

      y += 6;
    };

    addTitle("ArchAgent-R Architecture Report");

    addSection("Project", parsedResult.project_title);
    addSection("Description", parsedResult.project_description);
    addSection("Architecture Plan", parsedResult.requirements_output);
    addSection("Architecture Design", parsedResult.architecture_output);
    addSection("System Decomposition", parsedResult.decomposition_output);
    addSection("Architecture Review", parsedResult.validation_output);
    addSection("Technology Stack", JSON.stringify(stack, null, 2));
    addSection("Evaluation Scores", JSON.stringify(scores, null, 2));

    doc.save(`${projectTitle.replace(/\s+/g, "_")}_Report.pdf`);
  };

  const handleSaveDesign = () => {
    if (!parsedResult) {
      alert("Generate an architecture first.");
      return;
    }

    alert("Design is already saved in SQLite project history.");
  };

  return (
    <div className="canvas-studio-page">
      <header className="canvas-studio-header">
        <div className="canvas-title-area">
          <Link to="/dashboard" className="back-dashboard-btn">
            <ArrowLeft size={18} />
            Dashboard
          </Link>

          <div>
            <h1>{projectTitle}</h1>
            <p>Interactive system design generated by ArchAgent-R</p>
          </div>
        </div>

        <div className="canvas-toolbar">
          <button onClick={() => window.archagentFitView?.()}>
            <Maximize2 size={18} />
            Fit View
          </button>

          <button onClick={exportCanvasAsPNG}>
            <Download size={18} />
            Export PNG
          </button>

          <button onClick={exportReportAsPDF}>
            <FileText size={18} />
            Export PDF
          </button>

          <button className="save-canvas-btn" onClick={handleSaveDesign}>
            <Save size={18} />
            Save Design
          </button>
        </div>
      </header>

      <main className="canvas-full-body">
        <div className="canvas-full-card">
          <div className="canvas-full-title">
            <div>
              <Sparkles size={22} />
              <h2>Generated Architecture Design</h2>
            </div>

            <span>
              {architectureJson ? "Architecture Loaded" : "No Architecture"}
            </span>
          </div>

          {architectureJson ? (
            <>
              <DiagramCanvas architectureJson={architectureJson} />

              <div className="canvas-insights-grid">
                <div className="canvas-insight-card score-panel">
                  <div className="insight-title">
                    <ShieldCheck size={22} />
                    <h3>Architecture Score</h3>
                  </div>

                  <div className="score-main">
                    {scores.consistency_score || 0}%
                  </div>

                  <div className="score-list">
                    <div>
                      <span>Pattern Accuracy</span>
                      <strong>
                        {scores.architecture_pattern_accuracy || 0}%
                      </strong>
                    </div>

                    <div>
                      <span>Component Coverage</span>
                      <strong>{scores.component_coverage || 0}%</strong>
                    </div>

                    <div>
                      <span>Requirement Satisfaction</span>
                      <strong>{scores.requirement_satisfaction || 0}%</strong>
                    </div>

                    <div>
                      <span>Consistency</span>
                      <strong>{scores.consistency_score || 0}%</strong>
                    </div>
                  </div>
                </div>

                <div className="canvas-insight-card stack-panel">
                  <div className="insight-title">
                    <Cpu size={22} />
                    <h3>Technology Stack</h3>
                  </div>

                  <div className="stack-grid">
                    <div>
                      <Network size={18} />
                      <span>Frontend</span>
                      <strong>{stack.frontend || "React"}</strong>
                    </div>

                    <div>
                      <Server size={18} />
                      <span>Backend</span>
                      <strong>{stack.backend || "FastAPI"}</strong>
                    </div>

                    <div>
                      <Database size={18} />
                      <span>Database</span>
                      <strong>{stack.database || "PostgreSQL"}</strong>
                    </div>

                    <div>
                      <Layers3 size={18} />
                      <span>Queue</span>
                      <strong>{stack.message_queue || "RabbitMQ"}</strong>
                    </div>

                    <div>
                      <Cpu size={18} />
                      <span>AI Model</span>
                      <strong>{stack.ai_model || "Llama 3.2"}</strong>
                    </div>
                  </div>
                </div>
              </div>
            </>
          ) : (
            <div className="canvas-empty-state">
              <Network size={84} />
              <h2>No Architecture Generated</h2>
              <p>Go back to the dashboard and generate an architecture first.</p>

              <Link to="/dashboard" className="open-canvas-btn">
                Generate Architecture
              </Link>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

export default CanvasPage;